name: Deploy Bot

on:
  schedule:
    - cron: "0 13 * * *" # 台灣時間21:00，每天 21:00 執行
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
      LINE_USER_ID: ${{ secrets.LINE_USER_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Write railway_root.crt from secret
        run: |
          mkdir -p certs
          printf "%s" "${{ secrets.RAILWAY_CRT }}" | base64 -d > certs/railway_root.crt

      - name: Validate certificate with OpenSSL
        run: |
          openssl x509 -in certs/railway_root.crt -text -noout

      - name: Run Script
        env:
          REQUESTS_CA_BUNDLE: "${{ github.workspace }}/certs/railway_root.crt"
        run: python main.py
